### ISSUE TITLE
how to add codeium?

### ISSUE THREAD

**Issue by WillEhrendreich** [gsuuon/llm.nvim#29]
is there a way to add Codeium? I'm a big fan of it, but you don't really get the chat kind of experience like this with it in nvim. you get some completion stuff, with codeium.nvim. is it similar enough to do?

**Comment by gsuuon** [comment]
Hi @WillEhrendreich ! I'm not sure, is there a codeium API? I haven't tried out the codeium plugin yet. I imagine it's possible to figure out how their API works from codeium.nvim. Adding a provider only requires implementing the [interface](https://github.com/gsuuon/llm.nvim/blob/f814ae37eb9fb52bf79ce65aad0b78d905b5cdf4/lua/llm/provider.lua#L15) (really just `request_completion`).

**Comment by WillEhrendreich** [comment]
I legit have no idea, I know that the plugin downloads a server of sorts, though not the same as the ones for LSP, but it essentially sends a bunch of requests through cmp via Plenary jobs, and then uses those as autocomplete suggestions. I believe that the server isn't a full local llm, and I think it communicates with codeium servers via their api, however that looks. I don't if it's possible that one could look at the codeium language server code, I haven't myself seen it, but I haven't had the time to find out if that info is available and to what degree it's open for that.

**Comment by WillEhrendreich** [comment]
@pqn any thoughts?

**Comment by gsuuon** [comment]
I skimmed through codeium.nvim, the process looks pretty involved including downloading/running a closed source binary to provide the server. It doesn't look like they offer a public API, so this may be a no-go.

**Comment by gsuuon** [comment]
Closing since it doesn't look like this will be possible. If they ever offer a public API we should definitely add them as a provider.
